loft-sh/devpod

CONTRIBUTING.md
e2e/tests/ssh/ssh.go
e2e/tests/up/up.go

changed local to docker provider in CONTRIBUTING.md

---

docs/pages/telemetry.mdx
docs/sidebars.js

TSIA :) 
Feedback is welcomed!

docs: add telemetry page

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
SECURITY.md

- Create SECURITY.md
add issue template 
- bug report, feature request.
Fixes ENG-1397

add repo utility templates

---

docs/pages/developing-in-workspaces/inactivity-timeout.mdx

Add page for inactivity timeout in "Developing in a Workspace"

docs: add inactivity timeout page

---

pkg/netstat/netstat_util.go

fix: fix SA1019, replace ioutil.ReadDir with os.ReadDir

---

docs/pages/developing-in-workspaces/connect-to-a-workspace.mdx
docs/pages/developing-in-workspaces/create-a-workspace.mdx
docs/pages/developing-in-workspaces/devcontainer-json.mdx
docs/pages/developing-in-workspaces/what-are-workspaces.mdx
docs/pages/getting-started/quickstart-devpod-cli.mdx
docs/pages/getting-started/quickstart-vscode-browser.mdx
docs/pages/getting-started/quickstart-vscode.mdx
docs/pages/what-is-devpod.mdx

Updated VSCode to the spelling of VS Code in Docs

Updated VSCode to VS Code

---

desktop/package.json
desktop/src-tauri/src/custom_protocol.rs

fix(ui): don't send invalid custom protocol messages to UI on windows

---

e2e/tests/up/testdata/docker-compose-with-multi-stage-build/.devcontainer.json
e2e/tests/up/testdata/docker-compose-with-multi-stage-build/Dockerfile
e2e/tests/up/testdata/docker-compose-with-multi-stage-build/docker-compose.yaml
e2e/tests/up/testdata/docker-with-multi-stage-build/.devcontainer.json
e2e/tests/up/testdata/docker-with-multi-stage-build/Dockerfile
e2e/tests/up/up.go
pkg/devcontainer/build.go
pkg/dockerfile/parse.go

fix: wrong target selected when using multi-stage docker files

---

cmd/agent/container/credentials_server.go
pkg/credentials/server.go
pkg/devcontainer/setup/setup.go

link /home/root for jetbrains

---

desktop/src-tauri/build.rs
pkg/inject/inject.go
pkg/shell/shell.go

Signed-off-by: Thomas Kosiewski <thomas.kosiewski@loft.sh>

Stripping carriage returns from commands

---

.github/workflows/release.yaml

Try to keep subversions during builds with alien

CI: keep subversion when using alien

---

desktop/src-tauri/tauri.conf.json

Found via:
```
$ apt-cache show dev-pod
Package: dev-pod
Status: install ok installed
Priority: optional
Installed-Size: 46652
Maintainer: loft.sh
Architecture: amd64
Version: 0.1.4
Depends: libayatana-appindicator3-1, libwebkit2gtk-4.0-37, libgtk-3-0
Description: TODO: provide short description
TODO: provide long description
Description-md5: 6ff8c3d3eb424fcceff5603369234b2b
```

fix: update packaging description

---

pkg/shell/shell.go

Fixes #340.
Signed-off-by: Thomas Kosiewski <thomas.kosiewski@loft.sh>

Use interactive shells for command aliases

---

.github/workflows/release.yaml

Fixing rpm build process
This should ensure subversions are kept when using alien

CI: fix rpm building

---

pkg/shell/shell.go

Reverts #341
Signed-off-by: Thomas Kosiewski <thomas.kosiewski@loft.sh>

Reverts shell execution in interactive mode

---

.golangci.yaml
e2e/framework/framework.go
pkg/agent/agent.go
pkg/copy/copy_supported.go
pkg/devcontainer/compose.go
pkg/devcontainer/config/merge.go
pkg/devcontainer/config/substitute.go
pkg/driver/docker/build.go
pkg/inject/inject.go
pkg/log/stream_logger.go
pkg/workspace/workspace.go

Signed-off-by: Thomas Kosiewski <thomas.kosiewski@loft.sh>

Some more linter and style changes

---

pkg/workspace/workspace.go

fix: panic when creating workspace for a private gitlab repository

---

pkg/inject/inject.sh

With this, we go for the `sudo` route only if we can't actually write in the INSTALL_PATH
This way (and with the updated ssh provider defaults in the next release) We can work on remote machines that do not have sudo rights.
Resolves #354 
Resolves #306 
Resolves ENG-1421
Resolves ENG-1480

fix: do not use sudo, if it's not strictly needed.

---

pkg/agent/agent.go

fix: nil pointer

---

go.mod
go.sum
pkg/devcontainer/config/parse.go
vendor/github.com/tidwall/jsonc/LICENSE
vendor/github.com/tidwall/jsonc/README.md
vendor/github.com/tidwall/jsonc/jsonc.go
vendor/modules.txt

This will do a proper JSONC->JSON conversion in order to avoid problems with some devcontainer.json like the one in this repo:
https://github.com/kube-rs/kube
Resolves ENG-1438

fix: move to proper JSONC support

---

desktop/src/views/Workspaces/CreateWorkspace/CreateWorkspace.tsx

fix(ui): fix workspace name input validation

---

cmd/up.go
pkg/driver/docker/docker.go
pkg/ide/jetbrains/generic.go
pkg/options/resolve.go
pkg/provider/provider.go
providers/docker/provider.yaml

docker init & DOCKER_HOST & improve error output

---

docs/pages/managing-providers/add-provider.mdx

Hi,
This PR adds the Scaleway community provider to the docsumentation

docs: add Scaleway community provider to docs

---

hack/build-e2e.sh
hack/rebuild.sh
pkg/agent/inject.go
pkg/copy/copy.go
pkg/driver/kubernetes/pvc.go
pkg/extract/compress.go
pkg/extract/extract.go

fix: copy symlinks directly

---

docs/pages/managing-providers/add-provider.mdx

Hi,
This PR adds the Equinix provider to the list of community provider.

feat: add equinix community provider to list

---

pkg/ssh/server/ssh.go

This will use the libc utility `getent` to infere the user's login shell
Fallback to the old method if unsuccessful
Resolves ENG-1657

fix: add getent based login shell discovery

---

cmd/agent/docker_credentials.go
cmd/agent/git_credentials.go
cmd/agent/workspace/up.go
cmd/helper/http/request.go
cmd/provider/list-default-providers.go
pkg/agent/inject.go
pkg/devcontainer/feature/features.go
pkg/download/download.go
pkg/http/http.go
pkg/ide/jetbrains/generic.go
pkg/ide/openvscode/openvscode.go
pkg/ide/vscode/vscode.go
pkg/open/open.go
pkg/workspace/provider.go

Restore http  features like proxy handling

---

desktop/.eslintrc.cjs

chore: fix typo in .eslintrc.cjs

---

pkg/devcontainer/config/parse.go
pkg/driver/kubernetes/run.go

fix: parse issue & kubernetes driver issue

---

e2e/tests/up/testdata/docker-compose-env-file/.devcontainer/devcontainer.json
e2e/tests/up/testdata/docker-compose-env-file/.env
e2e/tests/up/testdata/docker-compose-env-file/docker-compose.yaml
e2e/tests/up/up.go
pkg/compose/helper.go

fix: docker-compose projects not loaded with dotenv files

---

e2e/tests/up/testdata/docker-compose-run-services/.devcontainer/devcontainer.json
e2e/tests/up/testdata/docker-compose-run-services/docker-compose.yaml
e2e/tests/up/up.go
pkg/devcontainer/compose.go

fix: docker-compose run all services by default

---

e2e/tests/ssh/ssh.go
pkg/devcontainer/run.go
pkg/language/language.go

with this PR we add:
- fallback to language detection when no image is specified in the devcontainer file
Fix #395 
Resolves ENG-1575

feat: fallback to universal image when none is specified in a devcontainer.json

---

cmd/up.go

fix: add warning to fleet

---

cmd/up.go
pkg/devcontainer/feature/extend.go
pkg/devcontainer/feature/features.go
pkg/provider/env.go
pkg/provider/workspace.go

fix: delete feature folder on failure

---

pkg/driver/kubernetes/pvc.go
pkg/options/resolve.go
pkg/provider/provider.go
providers/kubernetes/provider.yaml

This PR adds support to let users choose PVC access mode from the Kubernetes provider settings.

Add PVC Access mode support

---

cmd/agent/workspace/up.go
cmd/helper/get_workspace_config.go
e2e/tests/up/up.go
pkg/agent/tunnelserver/tunnelserver.go
pkg/git/git.go
pkg/git/git_test.go
pkg/provider/workspace.go
pkg/workspace/workspace.go

Allow checking out from commit hash

---

cmd/agent/container/setup.go
pkg/ide/vscode/vscode.go

fix: install alpine dependencies for vscode

---

desktop/README.md

Small improvements, which I'd like to have during my setup of local env.

Improved documentation for devpod local setup

---

desktop/src/constants.ts
desktop/src/types.ts
desktop/src/useAppReady.tsx
desktop/src/views/Providers/AddProvider/ConfigureProviderOptionsForm.tsx
desktop/src/views/Workspaces/helpers.ts

chore(ui): add support for git commit hash in workspace

---

cmd/provider/import_workspace.go
cmd/provider/provider.go
pkg/client/client.go
pkg/client/clientimplementation/proxy_client.go
pkg/provider/provider.go

- draft: implemented import_workspace command
- updated draft of import workspace cmd
- draft of handling import workspace in proxy client

workspace sharing

---

cmd/pro/import_workspace.go
cmd/pro/pro.go
cmd/provider/provider.go
hack/rebuild.sh

- moved import-workspace to devpod pro command
- changed flag devpod-pro-url to devpod-host
- Added logging to rebuild.sh script
- fix find provider method call argument

move import workspace to pro

---

.github/workflows/e2e-tests.yaml
pkg/driver/kubernetes/build.go
providers/docker/provider.yaml
providers/kubernetes/provider.yaml

fix: remove init for k8s & docker provider & improve pod-running-timeout

---

cmd/agent/docker_credentials.go
cmd/agent/git_credentials.go
pkg/agent/tunnelserver/tunnelserver.go
pkg/image/image.go

fix: be more forgiving with forwarded credentials

---

desktop/src-tauri/src/fix_env.rs

`printenv <VARIABLE>` returns only the value of the variable. We expected a format `PATH=...` and we were looking for `=` in the output (which was not there of course).
Apart from that the tests were doing nothing - they were testing only `std::env::set_env` and  `std::env::env` methods, which was pointless of course. I removed them.
Ensured that it works on my machine.
fixes ENG-1991

Fixed setting path; removed dummy unit tests

---

pkg/git/git.go
pkg/git/git_test.go

Fix clone ssh repo

---

pkg/ide/vscode/open.go

Reorder vscode command args

---

docs/pages/other-topics/mobile-support.mdx
docs/sidebars.js

chore(docs): add page for mobile support

---

cmd/ssh.go

Fix ENG-2107
Remove desktop notification

remove desktop notification

---

docs/pages/managing-providers/add-provider.mdx

Hi,
this PR adds the Exoscale provider to the list and removes my Hetzner provider, which is not working.

Add Exoscale provider

---

pkg/ssh/server/ssh.go

Fix ssh.getUserShell

---

cmd/agent/workspace/up.go

Resolve logic error in docker auto-instalation routine
Resolves ENG-2287

fix: resolve regression in docker auto-installation logic

---

cmd/up.go
pkg/devcontainer/setup.go
pkg/devcontainer/setup/setup.go
pkg/devcontainer/sshtunnel/sshtunnel.go

Closes ENG-2020
Closes ENG-2006
Closes #673

Refactor DevPod up command to allow SSH agent forwarding

---

README.md
docs/pages/getting-started/install.mdx

fix/remove some broken links from the README and install docs

Install doc fixes

---

pkg/devcontainer/sshtunnel/sshtunnel.go

Use correct context for the ssh server helper command

---

e2e/framework/command.go
e2e/tests/ssh/ssh.go
e2e/tests/ssh/testdata/forward-test/.devcontainer.json

Add test for --forward-ports/-L
Resolves ENG-2384

tests: add test for ssh port forwarding

---

docs/pages/other-topics/mobile-support.mdx

doc: mobile-support: add nix-on-droid instructions

---

docs/pages/developing-in-workspaces/credentials.mdx

INJECT_DOCKER_CREDENTIALS Key is wrong there is no as such key avlb

[fix]: Update credentials.mdx

---

community.yaml
docs/pages/managing-providers/add-provider.mdx

Add [Canonical Multipass](https://multipass.run/) provider

Add Multipass provider

---

e2e/framework/command.go
e2e/tests/provider/provider.go
pkg/workspace/provider.go

fix(cli): exclude non directories and DS_Store from providers list

---

cmd/ssh.go
cmd/up.go
pkg/ssh/config.go

fix(cli): append workdir to ssh ProxyCommand config if it is reported back from devcontainer creation

---

cmd/agent/workspace/install_dotfiles.go
cmd/agent/workspace/up.go
cmd/helper/get_workspace_config.go
e2e/tests/up/docker.go
pkg/git/git.go

fix(cli): resolve dotfiles repository string similar to workspace source

---

pkg/inject/inject.sh

Resolves ENG-2043
Fix #692 
Fail early during agent injection on noexec detection

fix: fail early during inject on noexec filesystems

---

desktop/src/Theme/theme.ts
desktop/src/client/context/contextCommands.ts
desktop/src/types.ts
desktop/src/views/Settings/Settings.tsx
desktop/src/views/Settings/useContextOptions.tsx

chore(ui): add telemetry toggle to settings > general; include link to telemetry docs

---

COMMUNITY.MD

Adding community calls to this Repo

docs: add community calls

---

e2e/tests/up/docker_compose.go
e2e/tests/up/docker_compose_build.go
pkg/compose/helper.go
pkg/devcontainer/compose.go

fix(cli): try to recreate docker compose project from existing configuration before resorting to a full blown rebuild

---

cmd/agent/workspace/up.go
pkg/agent/agent.go
pkg/config/config.go
pkg/copy/copy.go
pkg/devcontainer/build.go
pkg/devcontainer/compose.go
pkg/devcontainer/config/parse.go
pkg/devcontainer/feature/extend.go
pkg/devcontainer/setup/setup.go
pkg/dockercredentials/dockercredentials.go
pkg/driver/docker/build.go
pkg/envfile/envfile.go
pkg/extract/extract.go
pkg/gitcredentials/gitcredentials.go
pkg/ide/fleet/fleet.go
pkg/ide/openvscode/openvscode.go
pkg/ide/vscode/vscode.go
pkg/provider/dir.go
pkg/template/fill.go

Restrict file permissions to user-scope only when possible
Resolves ENG-3007

fix: restrict file permissions

---

.github/workflows/e2e-tests.yaml
e2e/tests/up/up.go

Add tests to ensure git credentials are properly forwarded
Resolves ENG-2989

tests: add git credentials e2e

---

cmd/agent/workspace/logs.go
cmd/agent/workspace/workspace.go
cmd/logs.go
cmd/root.go
pkg/agent/agent.go
pkg/devcontainer/run.go
pkg/docker/helper.go
pkg/driver/custom/custom.go
pkg/driver/docker/docker.go
pkg/driver/types.go
pkg/provider/parse.go
pkg/provider/provider.go

`devpod logs $WORKSPACE_ID`
resolves #958

feat(cli): add logs command to display the devcontainer logs; extend driver and runner interfaces to fetch logs

---

pkg/devcontainer/build.go
pkg/devcontainer/inspect.go
pkg/devcontainer/prebuild.go
pkg/docker/helper.go
pkg/driver/docker.go
pkg/driver/docker/docker.go

fix(build): fix invalid reference format condition when building and pushing from a compose file

---

pkg/workspace/workspace.go

fall back to git repository if none of the earlier options match,

chore: When resolving the workspace source

---

pkg/ide/vscode/vscode.go

v1.88.x, uses a new folder structure similar to vscode-insiders. Check for both the legacy location and the new one for backwards compatibility,

fix(vscode): The latest stable release of vscode

---

desktop/src-tauri/Cargo.toml
desktop/src-tauri/src/settings.rs
desktop/src/client/command.ts
desktop/src/contexts/SettingsContext.tsx
desktop/src/gen/Settings.ts
desktop/src/views/Settings/Settings.tsx
desktop/src/views/Settings/useContextOptions.tsx

feat(desktop): add experimental extra environment variables setting

---

desktop/src-tauri/src/settings.rs
desktop/src/client/client.ts
desktop/src/client/workspaces/client.ts
desktop/src/contexts/SettingsContext.tsx
desktop/src/gen/Settings.ts
desktop/src/views/Settings/Settings.tsx
desktop/src/views/Settings/useContextOptions.tsx

Add `dotfiles` customization option in GUI:
Resolves POD-205

feat(desktop): add customization settings for dotfiles

---

desktop/src/views/Workspaces/CreateWorkspace/CreateWorkspace.tsx
desktop/src/views/Workspaces/CreateWorkspace/WorkspaceSourceInput.tsx
desktop/yarn.lock
pkg/git/git.go

feat(desktop): show avaiable options in workspace source input field by structuring them and add advances git options

---

.github/workflows/release.yaml
docs/pages/getting-started/install.mdx

fix(build): fix appimage links in docs

---

cmd/agent/workspace/up.go
cmd/up.go
pkg/git/clone.go
pkg/git/git.go
pkg/provider/workspace.go

Add SSH keys project-wise, these will be then used for git-cloning in order to access private repos via SSH
Resolves POD-646

feat(pro): add project-wise SSH keys

---

cmd/agent/container/setup.go
cmd/up.go
desktop/src/images/rustrover.svg
main.go
pkg/config/ide.go
pkg/driver/docker/docker.go
pkg/ide/ideparse/parse.go
pkg/ide/jetbrains/rustrover.go

Add Rust Rover support
Fix #1092 
Resolve POD-668

feat(ide): add RustRover support

---

cmd/agent/container/credentials_server.go
cmd/helper/docker_credentials.go
cmd/helper/helper.go
pkg/credentials/server.go
pkg/credentials/start.go
pkg/dockercredentials/dockercredentials.go

Start credentials server on default port and allow overwrites through
DEVPOD_CREDENTIALS_SERVER_PORT env var

feat(cli): fix docker credential forwarding for azure container registry.

---

desktop/src-tauri/Cargo.lock
desktop/src-tauri/Cargo.toml
desktop/src-tauri/src/custom_protocol.rs
desktop/src-tauri/src/file_exists.rs
desktop/src-tauri/src/get_env.rs
desktop/src-tauri/src/install_cli.rs
desktop/src-tauri/src/log_message.rs
desktop/src-tauri/src/main.rs
desktop/src-tauri/tauri.conf.json
desktop/src/client/client.ts
desktop/src/client/command.ts

This PR aims to fix some issues when running Devpod into a flatpak

fix(build): add flatpak support

---

pkg/gitcredentials/gitcredentials.go

ref:
- https://git-scm.com/docs/git-config/#Documentation/git-config.txt-XDGCONFIGHOMEgitconfig
- gh-1171

fix(cli): git config path

---

cmd/pro/provider/list/templateoptions.go
desktop/src/views/Providers/AddProvider/OptionFormField.tsx
hack/pro/provider.yaml

Fixes an issue where changing the provider options in the GUI wouldn't
actually pass the new options to the CLI
Additionally, the pro provider now sends the option type based on the
parameter type

fix(desktop): change provider options

---

cmd/helper/get_workspace_config.go
pkg/devcontainer/helpers.go

POD-768 | Expose devcontainer config util funcs in package

---

cmd/pro/import_workspace.go

Fixes an issue where the import would fail if the template isn't
versioned

fix(pro): import non-versioned workspace template

---

pkg/workspace/workspace.go

Fixes https://github.com/loft-sh/devpod/issues/1189

Skip hidden files

---

cmd/agent/container/setup.go
cmd/agent/workspace/up.go
pkg/agent/workspace.go
pkg/devcontainer/config.go
pkg/devcontainer/crane/run.go
pkg/devcontainer/run.go
pkg/devcontainer/setup.go
pkg/provider/workspace.go

POD-854 | Decouple pulling devcontainer spec from pulling project

---

desktop/src/types.ts
desktop/src/views/Settings/ClearableInput.tsx
desktop/src/views/Settings/Settings.tsx
desktop/src/views/Settings/useContextOptions.tsx
desktop/src/views/Settings/useSettingsOptions.tsx

feat(desktop): Add context settings to toggle docker/git credential forwarding behaviour for default context from desktop app

---

pkg/tunnel/services.go

Fixes https://github.com/loft-sh/devpod/issues/793

Use errorf instead of debug log level

---

pkg/devcontainer/config/config.go

Fixes https://github.com/loft-sh/devpod/issues/1292

Support parsing "other" property from mounts

---

cmd/agent/container/setup.go

tl;dr: This should speed up dockerless builds for most users but
specially if you've been installing noisy dependencies
Due to how logs from remote workspaces need to be tunnel to the local
machine to be printed to a terminal, potentially over a network,
printing the stdout log output of kaniko ended up slowing down workspace
startup times quite significantly. This has mostly surfaced when
installing the AWS CLI. We still print stdout if you run `up` with
`--debug`.

fix(dockerless): Only listen to kaniko stdout if --debug is set.

---

cmd/ssh.go

Add ssh keepalive to tunnel to workspace

---

desktop/src/lib/modals/useLoginProModal.tsx

Revert "fix: Disable pro provider configuration for pro providers that suppor…"

---

pkg/driver/docker/docker.go

fixes https://github.com/loft-sh/devpod/issues/1462

Only have uid mapping for linux installations

---

desktop/src/Theme/theme.ts
desktop/src/components/Error/ErrorMessageBox.tsx
desktop/src/components/Warning/WarningMessageBox.tsx
desktop/src/views/Pro/CreateWorkspace/InfrastructureTemplateInput.tsx
desktop/src/views/Providers/AddProvider/OptionFormField.tsx
desktop/src/views/Workspaces/CreateWorkspace/ProviderOptionsPopover.tsx
desktop/src/views/Workspaces/WorkspaceCard.tsx

where users were not able to select text in DevPod Desktop

fix(desktop): set userSelect to text instead of auto to fix an issue

---

pkg/gitcredentials/gitcredentials.go

Fixes https://github.com/loft-sh/devpod/issues/1479

Fix use of single quotes when setting git username or email

---

docs/pages/troubleshooting/linux-troubleshooting.mdx

Document workaround for https://github.com/loft-sh/devpod/issues/1045

Update docs with workaround

---

docs/pages/getting-started/install.mdx

Add libgles2-mesa to install (fixes #1615)

---

cmd/agent/container/setup.go
pkg/devcontainer/setup.go
pkg/ts/connection.go
pkg/ts/derp.go
pkg/ts/workspace_server.go

POD-1321 | Add heartbeat to workspace ssh server

---

.github/workflows/release.yaml

Previous release failed on the last step - https://github.com/loft-sh/devpod/actions/runs/13585362085/job/37979033122#step:25:23
I used the wrong package version and path for the desktop file

Fix file paths

---

cmd/pro/start.go

FIX: Remove --insecure flag from pro start success message

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

chore: bump golang-jwt version
