.github/workflows/release.yaml
pkg/telemetry/collect.go
pkg/telemetry/helpers.go
pkg/telemetry/types/types.go

Small telemetry fix to fill in missing values in the `InstanceProperties` and set concrete `int64` type instead of `int`.
The release workflow has been updated to inject correct value for the `pkg/version.version` variable and also correct telemetry certificate.

Release process update + small telemetry fix

---

.github/workflows/release.yaml
desktop/README.md
desktop/src-tauri/tauri-linux.conf.json

Right now tauri builds with `visible: false` are creating sparse problems with windows not appearing in some distributions.
For now we'll disable that on linux

fix: linux transparency issue

---

hack/rebuild.sh

With the current rebuild.sh, root is required to have golang installed as ````sudo go build```` is done.
This PR allow the build to be done under the current user and then sudo is only required to move the build into destination folder

fix hack/rebuild.sh to not required root to have go installed

---

.github/ISSUE_TEMPLATE/bug-report.md

`version` is a command rather than a `--version` flag.

Correctly specify how to find DevPod version

---

e2e/e2e_suite_test.go
e2e/framework/agent_server.go
e2e/tests/up/testdata/docker-compose-forward-ports/.devcontainer.json
e2e/tests/up/testdata/docker-compose-forward-ports/docker-compose.yaml
e2e/tests/up/up.go
pkg/devcontainer/config/config.go
pkg/devcontainer/config/merge.go
pkg/tunnel/services.go
pkg/types/types.go

fix: add support for "host:port" forwardPorts syntax

---

pkg/driver/docker/docker.go

`runArgs` set in `devcontainer.json` are currently parsed by DevPod, but they are not added when the `docker run` command is issued.
This change passes `runArgs` into the `docker run` command.
--------------------------------
I found the need for `runArgs` as I was attempting to set up multiple containers that could communicate with each other.  Docker Compose is often used for this scenario, but I needed to work with Docker networking directly.
Being able to pass the `runArgs` to the `docker run` command allowed me to achieve this:
```
{
"name": "devpod-test",
"build": {
"dockerfile": "Dockerfile"
},
"initializeCommand": "docker network inspect test-network >/dev/null 2>&1 || docker network create --driver bridge test-network",
"runArgs": [
"--name=devpod-test",
"--network=test-network" …
```

Pass runArgs from devcontainer.json into docker run command

---

pkg/agent/agent.go
pkg/docker/helper.go
pkg/driver/docker/build.go
pkg/driver/docker/docker.go
pkg/options/resolve.go
pkg/provider/provider.go

1. in some places docker command is hard written such as [dockerReachable](https://github.com/loft-sh/devpod/blob/7ec3edaf696fac8169e84a61a6bc7cb51e91212a/pkg/agent/agent.go\#L324), it can cause problems since the command may not exists or not the one that should be called since we explicitely provide another one
2. in some cases it will be helpfull to pass some enviromnent variables to the command, such as DOCKER_HOST, etc... So for that i added a new envs mapping into the driver docker agent section:
```
docker:
path: /my/custom/command
envs:
DOCKER_HOST: "${API_BASE_URL}"
...
KEY: VALUE
install: false
```

replace hard written docker with workspaceInfo.Agent.Docker.Path + allow env variables to be passed into docker command

---

pkg/copy/copy.go
pkg/ide/openvscode/openvscode.go

When using Openvscode (Web Vscode) with Docker, a process keeps 1 core of the cpu binned to 100%.
This does not happen in Podman.
Turns out this is because of a permission problem, where the `.openvscode` directory had some inaccessible files/dirs for permissions.
This PR fixes this, and contextually upgrades openvscode to the latest release v1.78.2

fix: resolve openvscode process eating CPU when using docker

---

pkg/docker/helper.go
pkg/driver/docker/docker.go

Right now deleting a workspace will leave its docker volumes behing
This implements the volume deletion when removing a devcontainer

fix: implement volume deletion when removing a devcontainer

---

pkg/dockerfile/parse.go

I just fall on this bug today with  fatal agent error: panic: runtime error: index out of range [2] with length 2 goroutine 1.
And after investigating found that [i is incremented when it should be decremented](https://github.com/loft-sh/devpod/blob/204d0decc41768ff5494c396462220c948d14995/pkg/dockerfile/parse.go#L141)  also [here](https://github.com/loft-sh/devpod/blob/204d0decc41768ff5494c396462220c948d14995/pkg/dockerfile/parse.go#L127)

fix panic : fatal agent error: panic: runtime error: index out of range [2]

---

docs/pages/managing-providers/add-provider.mdx

The SSH provider's YAML file is actually a template which is prepared for release by GitHub Actions. Targeting it with `devpod provider add` results in an error, users should target the GitHub release download instead.

fix: update add provider from url example to use a working url

---

cmd/provider/list-default-providers.go
cmd/provider/provider.go
docs/pages/managing-providers/add-provider.mdx

This should ease the life of a CLI-only user.
It gets on par with what is already available on GUI, a list of our 1st party providers ready to install.
Resolves ENG-1326

feat: add provider command to list installable providers

---

docs/pages/managing-providers/add-provider.mdx

Added a section containing some community-supported providers. Aside from a [provider I did this weekend](https://github.com/mrsimonemms/devpod-provider-hetzner), the others are from a [message in Slack](https://loft-sh.slack.com/archives/C056ZDZPJ4W/p1686571333877349) and from a [tweet retweeted by @devpod](https://twitter.com/OVHcloud_Tech/status/1665635676799266820).
The idea is to provide a centralised list of providers for the benefit of the community, but without DevPod engineers having to increase what they support.

docs: add community providers section

---

pkg/driver/docker/docker.go

This PR will fix support for rootful (non-rootless) podman
userns keep-id is reserved only for rootless podman, so let's check if we're root before adding the flag

fix: handle rootful podman

---

cmd/delete.go
providers/kubernetes/provider.yaml

Right now the k8s init wasn't working properly, allowing for invalid kubeconfig paths, and values
Contextually this would lead to `delete` to not actually delete the workspace dir, thus making the user stuck with the "wrong" config, not able to update it and requiring manual intervention.
Resolves ENG-1600

fix: properly check kubectl success on init. Force workspace folder deletion

---

pkg/inject/inject.sh

This will
Fix #464 
Resolve ENG-1676
Setop is needed on ZSH if it's directly called as such, so let's allow it to fail in case

fix: make setopt command not fail

---

pkg/inject/inject.sh

Don't download/inject to the same inode, in case it is already in use.
This PR takes the conservative approach of writing to a tempfile and then
renaming over the original in a second step.  This means a later (failed)
download/inject won't corrupt any existing file.
Fixes "Text file busy" error:
```
16:57:57 info Inject binary
16:57:57 info done exec
16:57:58 info Done injecting binary
16:57:58 info done inject
16:57:58 info done injecting
16:57:58 info Inject Error: sh: 1: cannot create /usr/local/bin/devpod: Text file busy
16:57:58 info write |1: file already closed
```

Avoid "Text file busy" during download/injection

---

.gitignore
e2e/e2e_suite_test.go
e2e/tests/integration/framework.go
e2e/tests/integration/integration.go
e2e/tests/integration/testdata/.devcontainer.json

This will add a new tests that runs the integration with the ssh-provider
This goes in hand with https://github.com/loft-sh/devpod-provider-ssh/pull/6 in order to test
compatibility both on devpod changes and provider changes.

tests: add integration tests for SSH provider

---

pkg/git/git.go
pkg/git/git_test.go

DevPod supports already creating workspaces from non-default branch by providing repository URL in the form of
`repository.host.abc/user/repo.git@branch`
With this change it accepts branches that contain slash in the name as this is common to name branch like `username/some-description`

Support workspaces from branches with slash in the name.

---

pkg/ide/jetbrains/phpstorm.go

The latest PhpStorm version is now 23.1.3. This updates the default version installed to that.

Increment PhpStorm version to 2023.1.3

---

cmd/agent/workspace/up.go

Introduced in https://github.com/loft-sh/devpod/commit/350fac9f6ff85a825559ecbe809ef3e3ae8245f6 was a logic error where if `CloneRepository` succeeds without an error, the function is not exited and is caught by the catch-all 
```
return fmt.Errorf("either workspace repository, image or local-folder is required")
```
This PR updates the function so that if there's no error returned from `CloneRepository`, the function exits.

fix: escape function after successful clone

---

examples/object-lifecycle-hooks/.devcontainer.json
pkg/devcontainer/config/config.go
pkg/devcontainer/config/merge.go
pkg/devcontainer/run.go
pkg/devcontainer/setup/setup.go
pkg/types/types.go
pkg/types/types_test.go

Following on from #380, this is a second attempt at solving #163 thanks to @pascalbreuninger's previous review.
Fixes #163 
This converts objects to an array of strings using a parallel Bash command. This does assume that `bash` is present on the devcontainers, which is probably a safe bet but I guess we could switch to `sh` if necessary.

fix(#163): handle objects in the devcontainer lifecyle hooks

---

e2e/tests/up/testdata/docker-features-lifecycle-hooks/.devcontainer.json
e2e/tests/up/up.go
pkg/devcontainer/single.go

With this PR we are building the remoteEnv from the containerEnv which is gathered from the container. This helps any lifecycle hooks to run with the proper environment set.
Fixes #522 
Fixes ENG-1742

Fix lifecycle dependency failures

---

pkg/driver/kubernetes/run.go

Hello,
I just tested the latest release, and the pod manifest template feature was not working as expected.
the env vars and volume mounts were not kept from the template.
This patch fix it

Fix pod manifest template

---

cmd/agent/workspace/install_dotfiles.go
cmd/agent/workspace/workspace.go
cmd/up.go
docs/pages/developing-in-workspaces/dotfiles-in-a-workspace.mdx
docs/sidebars.js
e2e/tests/up/up.go
pkg/config/context.go

This PR adds support for cloning a dotfiles repo during workspace creation
Such repo will be cloned in the main container's user's HOME, and the following script locations will be checked to find install scripts:
- install.sh
- install
- bootstrap.sh
- bootstrap
- script/bootstrap
- setup.sh
- setup
- setup/setup
If no script is found, it will simply link all dotfiles in the root of the repo into $HOME.
Additional script locations can be specified in order to support custom install scripts, for example, for my dotfiles repo https://github.com/89luca89/dotfiles I can specify `bin/.local/bin/dotfiles` that will perform the installation.
Repo URL and script locations can be specified either via command flags in the `up` command:
```sh
devpod up my-project --dotfiles …
```

feat: add dotfiles repo support

---

e2e/tests/build/build.go
e2e/tests/up/testdata/docker-dockerfile-buildcontext/.devcontainer/devcontainer.json
e2e/tests/up/testdata/docker-dockerfile-buildcontext/.dockerignore
e2e/tests/up/testdata/docker-dockerfile-buildcontext/Dockerfile
e2e/tests/up/testdata/docker-dockerfile-buildcontext/scripts/alias.sh
e2e/tests/up/testdata/docker-dockerfile-buildcontext/scripts/install.sh
e2e/tests/up/up.go
go.mod
pkg/devcontainer/config/prebuild.go
pkg/driver/docker/build.go
pkg/driver/kubernetes/build.go
pkg/util/hash/hash.go
vendor/github.com/docker/docker/pkg/longpath/longpath.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerignore/dockerignore.go
vendor/modules.txt

With this PR, we will build a hash for the contents in the build context and append it to the Prebuild Hash. This will cause any changes to files under the build context to be picked up while rebuilding the workspace.
Fixes ENG-1797

Rebuild on changes to files in build context

---

docs/pages/developing-in-workspaces/environment-variables-in-devcontainer-json.mdx
docs/pages/getting-started/quickstart-ssh.mdx
docs/sidebars.js

Fixes ENG-1729
A user encountered some problems with a setup of his workspace when using env variables in devcontainer.json and passing them through the ssh: https://github.com/loft-sh/devpod/issues/507 
I'm adding here an instruction which I send him to verify he didn't forgot about anything.

Prepared documentation for using env variables in devcontainer json

---

pkg/git/git.go
pkg/git/git_test.go

With this PR we are adding support for "_" (underscores) in branch name for workspace source specified in <git-repository>@<branch-name> format.
Fixes #600 
Closes ENG-1853

Support _(underscores) in branch name for git repo sources

---

pkg/driver/kubernetes/run.go

PR #547 added support for a `podManifestTemplate` which claimed to fix Issue #390 (although not via `portsAttributes` but via the template).
I suspect `ports` in the manifest worked in that PR and were broken by https://github.com/loft-sh/devpod/commit/4be34b237a9653630ae687453b72117908bdc854 which did some good refactoring, but made it necessary to copy the parameters you wanted rather than basing the pod on the manifest directly.
I would like both `ports:` and `envFrom:` to work, and this commit fixes both of those to come from the template. If they are unspecified in the manifest they will be unset in the created pod too.

fix: Support Ports and EnvFrom in kubernetes manifest

---

cmd/agent/workspace/build.go
e2e/tests/build/build.go
pkg/devcontainer/prebuild.go

With this PR we
1. Allow devpod build without specifying pre-build repository , if --skip-push is true
2. Update info/debug messages appropriately
Closes ENG-1855

Make the repository flag optional if --skip-push is set for devpod build

---

e2e/tests/up/testdata/docker-compose-rebuild-fail/fail.devcontainer.json
pkg/compose/helper.go
pkg/devcontainer/compose.go

With this PR, we add the compose files and env files paths to the devpod stop and delete commands so that they can be run regardless of the location of docker-compose.yaml .
Closes ENG-1910
Closes #623

Add composeGlobalArgs to Devpod Stop and Delete commands

---

e2e/tests/build/build.go
e2e/tests/build/testdata/docker-compose/.devcontainer/Dockerfile
e2e/tests/build/testdata/docker-compose/.devcontainer/devcontainer.json
e2e/tests/build/testdata/docker-compose/.devcontainer/docker-compose.yaml
pkg/devcontainer/build.go
pkg/devcontainer/compose.go
pkg/devcontainer/run.go

With this PR, we enable devpod build to fetch the image name of the referenced service from the service definition in docker-compose file.
P.S. Subsequently pushing the above image is not possible currently and would be discussed and worked upon
Closes ENG-1866
Closes #606

Image from docker compose file

---

cmd/provider/import_workspace.go

- moved context resolving to separate method
- resolve workspace folder based on other arguments instead of flag
- prepared provider resolver to take care of finding exact provider
- moved Run command up
- cleanup of flags

import workspace cmd arguments

---

cmd/agent/workspace/up.go
cmd/helper/get_workspace_config.go
e2e/tests/up/up.go
pkg/agent/tunnelserver/tunnelserver.go
pkg/git/git.go
pkg/git/git_test.go
pkg/provider/workspace.go
pkg/workspace/workspace.go

With this PR we support checkout from a PR Reference, so that below should be possible now.
```devpod up <repo-name>@pull/<PR-number>/head```
Closes ENG-1842

Support checkout from PR Reference

---

.github/workflows/release.yaml

Building on older systems allows for dynamic linking on older GLIBC and libssl libraries.
Those are automatically resolved for newer versions on newer systems, so this does not break forward compatibility
Fix #461 
Resolves ENG-1674
Needs feedback from users and some testing before merging

fix: use ubuntu-20 image for linux builds

---

cmd/pro/import_workspace.go
desktop/src/useAppReady.tsx
pkg/client/clientimplementation/proxy_client.go

Resolves ENG-1992 
Message for invalid devpod pro host:
Message for not-existing workspace:
Unsupported host:
There is one last case which left - if we lack some id / parameter, we get only "invalid query" error. I spend some time debugging it, but couldn't figure out why the message is not passed to the UI. I'll spend some more time on that, but don't want to block the whole process by only this one case.

improvements to error handling in import-workspace

---

pkg/agent/inject.go
pkg/inject/filesystem_linux.go
pkg/inject/filesystem_other.go
pkg/inject/inject.go

Fix ENG-2043
Tested locally by manually switching `isNoExec()` return value for mac from `false` to `true`

fail fast if mounted filesystem for agent is noexec

---

pkg/ide/vscode/open.go

fix(cli): separate --folder-uri and arg with = instead of whitespace

---

cmd/up.go

This way now we will default to the container user (usually vscode) and fallback to root otherwise
Fix #655 
Resolves ENG-1975

fix: setup-dotfiles should be ran as the default user

---

pkg/devcontainer/build.go
pkg/devcontainer/compose.go
pkg/devcontainer/feature/extend.go
pkg/devcontainer/feature/features.go
pkg/driver/docker/build.go

Two fixes for the force-build flag that is very useful when building new features
First is the build is no triggered when the flag is used without a repository (so with skip-push)
Second is to force the redownload of the package when using archive on a https server

Small fixes to force-build

---

docs/pages/developing-in-workspaces/create-a-workspace.mdx

Closes: https://github.com/loft-sh/devpod/issues/626
After following down the chain found that there is the option to set the home path for mounts. Passing the flag allows to set the desired home directory, which is then later used for building mount paths.
This can allow someone to set or change where the mounts should be happening by specifying the homedir either as flag or env var

add info on setting home dir

---

.github/workflows/release.yaml
docs/pages/getting-started/install.mdx

This PR deprecates the DEB and RPM Packages for linux
We'll officially support only the Appimage built by tauri
We'll also provide a tar.gz that can be used separately or for people that want to create their own packages
Also document the necessary dependencies to run the Appimage, and dependencies needed to run the tar.gz
Resolves ENG-1629
Resolves ENG-2135

chore: refine AppImage dependencies and docs, create a tar.gz deployment

---

cmd/helper/ssh_server.go
cmd/ssh.go
pkg/ssh/server/ssh.go

Fixes #730
I didn't go as far as adding a `--workdir` argument to `devpod ssh` as suggested in https://github.com/loft-sh/devpod/issues/730#issuecomment-1759072845 because it isn't strictly necessary.
Looking forward to feedback.
Should this be tested in any way?

Set SSH working directory

---

pkg/ide/fleet/fleet.go

Simple fix for fleet not starting after a first setup
Resolves ENG-2218

fix: fleet should start if already installed

---

cmd/agent/container/setup.go
cmd/agent/workspace/up.go
e2e/tests/up/up.go
pkg/devcontainer/run.go
pkg/devcontainer/setup/setup.go
pkg/devcontainer/sshtunnel/sshtunnel.go
pkg/ide/vscode/vscode.go

Generally improve STDERR logging by using the error level instead of info level
Add more messages to postcreate command execution
Giving now a more clear and first-glanceable output
Fix #775 
Resolves ENG-2298

fix: improve error logging across commands and postcreate commands

---

README.md

Twitter is now known as 𝕏.
So we should reflect it in our repository.
This fixes https://github.com/loft-sh/devpod/issues/791

chore: In README.md Twitter's new name updated to 𝕏. 

---

pkg/ide/jetbrains/clion.go
pkg/ide/jetbrains/goland.go
pkg/ide/jetbrains/intellij.go
pkg/ide/jetbrains/phpstorm.go
pkg/ide/jetbrains/pycharm.go
pkg/ide/jetbrains/rider.go
pkg/ide/jetbrains/rubymine.go
pkg/ide/jetbrains/webstorm.go
pkg/ide/openvscode/openvscode.go

Update IDE versions
OpenVSCode -> 1.83.0
Clion -> 2023.2.2
Golang -> 2023.2.4
Intellij -> 2023.2.4
PhpStorm -> 2023.2.3
PyCharm -> 2023.2.3
Rider -> 2023.2.3
RubyMine -> 2023.2.4
Resolves ENG-2339

chore: update IDE versions

---

pkg/driver/docker/docker.go

Resolve regression where running docker commands with "RunWithDir" breaks compatibility with WSL filepaths on Windows
Fix #644 
Resolve ENG-1965

fix: revert regression introduced in 0a40554 for WSL systems

---

pkg/ssh/server/ssh.go

Ensure /tmp exists, this will fix issues for creating tmpfiles and tmpdirs in container environments
Fix #805 
Resolves ENG-2398

fix: ensure /tmp exists to have a consistent dir structure

---

cmd/up.go

This fixes a behavioural bug,
if we specify the `--gpg-agent-forwarding` during `up`, we expect it to take immediate effect when using our IDE
This fixes the inconsistency
Resolves ENG-1900

fix: launch gpg-forwarding during UP if flag is specified

---

.github/workflows/e2e-tests.yaml
e2e/framework/exec.go
e2e/framework/framework.go
e2e/framework/util.go
e2e/tests/build/build.go
e2e/tests/machineprovider/machineprovider.go
e2e/tests/proxyprovider/proxyprovider.go
e2e/tests/ssh/ssh.go
e2e/tests/up/docker.go
e2e/tests/up/docker_compose.go
e2e/tests/up/podman.go
e2e/tests/up/up.go

This PR will add a test step for windows
Not all e2e tests are yet compatible with Windows, but it's a starting point
Resolves ENG-2368

tests: add Windows E2E testing

---

.github/workflows/release.yaml

While packaging this as an RPM, xdg-open and glib-2.0 were found in the Linux tar.gz archive.
Looking into this further, I extracted the last built RPM and saw that neither xdg-open nor the glib-2.0 schemas were there.
This excludes both from the release workflow.

fix(cd): Exclude xdg-open and glib-2.0 schemas from Linux tar.gz

---

cmd/agent/workspace/delete.go
cmd/agent/workspace/up.go
e2e/tests/up/docker.go
pkg/devcontainer/config/config.go
pkg/devcontainer/config/container_details.go
pkg/devcontainer/run.go
pkg/devcontainer/single.go
pkg/docker/helper.go
pkg/driver/docker/docker.go
pkg/provider/workspace.go
pkg/workspace/workspace.go

feat: support setting up existing container as devcontainer

---

community.yaml
docs/pages/managing-providers/add-provider.mdx

Added support for Open Telekom Cloud, the OpenStack-based public cloud offering of the German leading IT services provider T-Systems International GmbH. 
That is a community project, not an officially supported one by T-Systems International GmbH.

added opentelekomcloud as a community provider

---

e2e/framework/command.go
e2e/tests/ssh/ssh.go
pkg/driver/docker/docker.go
pkg/gpg/gpg_forwarding.go

Tmps commit broke GPG forwarding, this PR will rever that
Also we were having false-positive e2e testing, as the command was failing silently
Fix #881 
Resolves ENG-2749

Fix GPG Agent forwarding broken

---

.github/workflows/e2e-tests.yaml
.github/workflows/e2e-win-full-tests.yaml
cmd/agent/workspace/up.go
cmd/helper/get_workspace_config.go
cmd/up.go
e2e/tests/ssh/ssh.go
e2e/tests/up/up.go
pkg/devcontainer/run.go
pkg/git/git.go
pkg/git/git_test.go
pkg/provider/workspace.go
pkg/workspace/workspace.go

Initial draft to support specifying a subpath where to start a workspace
When specified the subpath will be used as:
- default workdir via ssh
- default workspace for IDEs
- default path where to search for devcontainer.json
Full project will anyway be cloned and mounted into the container
Useful for monorepos
Resolves ENG-1976
I'm still not sure if this is the best way to do it, but it works for now, want to discuss here the implementation in the GUI, and if there are missing pieces
EDIT: to change subfolder, you use `--recreate` also, so it can switch also container

feat: start workspace in a subpath

---

pkg/devcontainer/config/config.go
pkg/devcontainer/config/merge.go

portAttributes are keyed by port, otherPortsAttributes are the
fallback for unnamed ports.

otherPortsAttributes should be the attributes directly

---

pkg/devcontainer/single.go
pkg/driver/docker/docker.go

Inject the following env variables in the container:
REMOTE_CONTAINERS=true
DEVPOD=true
This will ensure that scripts and software running inside can detect that we are in a remote, devpod, container.
Fix #891 
Resolves ENG-2793

feat: inject DEVPOD and REMOTE_CONTAINERS env variables

---

pkg/dockercredentials/dockercredentials.go

This will ensure Azure credentials work on docker
Fix #743 
Resolves ENG-2244

fix: set Azure username credentials if empty

---

pkg/devcontainer/feature/options.go

Feature variables were pulled from a map, leading to random ordering. This caused the docker context to be randomly slightly different leading to build cache misses.

fix: sort feature variables to improve caching

---

.github/workflows/e2e-tests.yaml
.github/workflows/e2e-win-full-tests.yaml

Fix Windows Runner piling up images with `devpod` and `none` tags

fix: Windows Runner cleanup

---

cmd/agent/workspace/up.go
e2e/framework/command.go
e2e/tests/up/up.go

If a workspace is created from an actual local folder (as opposed to downloading a git repo) _and_ we're using a local provider, then `--recreate` should not try to download that folder again.
Without this fix I was seeing an EOF issue on recreate (likely files were trying to be copied to / from the same destination leading to file corruption). For example, my `.git/index` file was being corrupted by this issue, leading to git commands causing a segfault.

fix: fix recreate logic if workspace is local folder

---

pkg/devcontainer/build/options.go
pkg/devcontainer/buildkit/buildkit.go
pkg/devcontainer/config/config.go
pkg/driver/docker/build.go

cli build options were recently added to the devcontainer spec (see https://github.com/devcontainers/spec/commit/d424cc157e9a110f3bf67d311b46c7306d5a465d ). let's add them here as well.
This can be useful for example to add a `--secret ...` to a `docker build`.
It's a little unclear currently how to add these to `pkg/devcontainer/buildkit/buildkit.go`. For now, I left a TODO. This would be no worse than the current behavior (as currently `build.options` is just ignored).

feat: add build cli options for buildx

---

pkg/docker/helper.go
pkg/driver/docker/docker.go

Denoise output for container pulling, moving the download progress to debug level.
To ensure this, we will inspect the image and pull it in a separate step before proceeding with the run command, this gives us the flexibility to relegate only the pull progress to debug output.
Regular output:
Debug output:
Resolves ENG-2936

feat: move docker pull output to debug, denoise output

---

desktop/src/views/Workspaces/WorkspaceCard.tsx

Adding a menu entry to show workspace logs, to improve discoverability of this feature
Fix #922 
Resolve ENG-2900

feat: add dedicated logs entry in meatball menu

---

.github/workflows/e2e-tests.yaml
.github/workflows/e2e-win-full-tests.yaml

Improve Windows Runner image cleanup at the end of e2e tests
This should reduce flackyness
Resolves ENG-2969

fix: improve cleanup images for windows runners

---

.github/workflows/e2e-tests.yaml
.github/workflows/e2e-win-full-tests.yaml
e2e/e2e_suite_test.go
e2e/framework/server_utils.go
pkg/agent/inject.go

add way for non-linux runners to download a freshly compiled devpod binary as agent
Resolves ENG-3057

fix(test): fix agent url on non-linux runners

---

cmd/up.go
e2e/tests/up/up.go
pkg/devcontainer/config/parse.go
pkg/provider/workspace.go

Fixes #827
Each file from the list is parsed for key value pairs in the format `key=value` and merged with the remaining `--workspace-env` variables.

feat: add support for devcontainer up --workspace-env-file

---

pkg/ssh/config.go

Fails to connect to DevPod on Windows over SSH since path for ProxyCommand in outputted `.ssh/config` is grabbed via `os.Executable()`, the default install location on Windows (`C:\Program Files`) has a space resulting in line:
```
ProxyCommand C:\Program Files\.... ssh --stdio --context default --user devpod workspace-1"
```
Fixed by wrapping the path in escaped quotations

Fix/SSH Conf: Generated ProxyCommand line is missing quotes around path

---

pkg/ide/jetbrains/clion.go
pkg/ide/jetbrains/generic.go
pkg/ide/jetbrains/goland.go
pkg/ide/jetbrains/intellij.go
pkg/ide/jetbrains/phpstorm.go
pkg/ide/jetbrains/pycharm.go
pkg/ide/jetbrains/rider.go
pkg/ide/jetbrains/rubymine.go
pkg/ide/jetbrains/webstorm.go

Additionally, retain override hook from `~/.devpod/config.yaml`.
Product codes can be found here:
https://youtrack.jetbrains.com/issue/MP-2363/Can-you-provide-me-the-list-of-jetbrains-product-codes

Download latest version of Jetbrains tools by default

---

.github/workflows/e2e-tests.yaml
.github/workflows/e2e-win-full-tests.yaml
.github/workflows/go-licenses-check.yaml
pkg/docker/helper.go
pkg/driver/docker/build.go
pkg/driver/docker/docker.go
pkg/driver/drivercreate/create.go
pkg/options/resolve.go
pkg/provider/provider.go
pkg/provider/workspace.go
providers/docker/provider.yaml

This PR solves #984 by first checking if podman is used when buildxExists is called and return true in this case.
It also adds a DOCKER_BUILDER option to the provider in order to choose easily between the 2 builders.

Add docker builder option to provider

---

pkg/agent/agent.go
pkg/devcontainer/sshtunnel/sshtunnel.go

When performing ssh clones on a machine where the Docker socket requires administrative access to utilize passing over the environment variables into the `sudo` session is required. 
It should also be noted, that Windows ships with OpenSSH 8.1 by default, so if Windows users are having issues with SSH Agent support they may need to upgrade their OpenSSH distribution to be inline or newer than the target machine's environment.

Preserve environment variables through sudo session

---

cmd/agent/workspace/install_dotfiles.go
cmd/agent/workspace/up.go
cmd/build.go
cmd/helper/get_workspace_config.go
cmd/up.go
pkg/git/clone.go
pkg/git/git.go
pkg/provider/workspace.go

feat(cli): add different git cloning strategies and respective CLI flag --git-clone-strategy for git based workspaces. Possible values are: 
- "" (full clone, default behaviour) 
- blobless (full commit history and trees, no blobs) 
- treeless (full commit history, no trees nor blobs) 
- shallow (current HEAD, no history)

feat(cli): add different git cloning strategies 

---

.github/workflows/release.yaml
docs/pages/getting-started/install.mdx

Create two appimages, one for newer releases (glibc new) and one for older releases (glibc old)
Fix #1059 
Resolves POD-639

fix(build): provide appimages for older glibc versions

---

cmd/ssh.go
cmd/up.go

force git credentials forwarding when setting up dotfiles

fix(cli): git credentials forwarding on vscode with private dotfiles

---

pkg/compose/helper.go

Fixing `11:48:19 info Invalid character(s) found in major number "v2"` error received from `semver` package as my docker compose version is `v2.2.3`

fix: trim v from semver

---

.github/workflows/release.yaml
docs/pages/getting-started/install.mdx

Basically revert all the "glibc-old" compatibility commits
We need glibg 2.35+
Update the compatibility list to reflect this

fix(build): abolish builds for too old glibc.

---

pkg/copy/copy.go
pkg/devcontainer/setup/setup.go

Make /workspace owned by vscode (or default user)
This will allow users to clone manually other projects if needed
Fix #1074 
Resolve POD-663

fix(workspace): make /workspace owned by default user

---

pkg/inject/download_urls.go

The arg will be substituted with the agent binary name to allow for
more customized Agent URLs like presigned s3 URLs
solves #1102

feat(cli): allow users to specify AGENT_URL with ${BIN_NAME} argument

---

cmd/stop.go
e2e/framework/command.go

Adds alias `down` for `stop` command to make CLI a bit more consistent - `devpod up` now has counterpart of `devpod down`
Fixes typo in `e2e/framework/command.go:DevPodStatus`

Add alias for `stop` command

---

pkg/devcontainer/setup/setup.go

Fixes issue where everything sent to stderr by postCreateCommand was logged as error by devpod
```
13:15:27 info Creating devcontainer...
13:15:27 info Inspecting image mcr.microsoft.com/vscode/devcontainers/python
13:15:27 info a8e8a369f917aa05b34e84a115077384c4c63d9c09cd12904d0c7672003966f9
13:15:28 info Setup container...
13:15:29 info Chown workspace...
13:15:29 info Run command : pipx install uv...
13:15:29 error creating virtual environment...
13:15:29 error installing uv...
13:15:30 error done! ✨ 🌟 ✨
13:15:30 info installed package uv 0.2.18, installed using Python 3.12.3
13:15:30 info These apps are now globally available
13:15:30 info - uv
13:15:30 done Successfully ran command : pipx install uv
13:15:30 info Install extensions …
```

Add filtering of postCreateCommand stdout stderr logs

---

cmd/agent/container/credentials_server.go
pkg/agent/tunnelserver/tunnelserver.go
pkg/gitcredentials/gitcredentials.go

When setting up .gitconfig in the workspace we attempt to read existing
settings and only fetch the user and email from the host machine if they
aren't already defined.
This never worked because we run the credentials server as root, thus
reading `git config --global user.xxx` from the root users gitconfig
which doesn't exist by default.
We now use retrieve the global gitconfig location by following
https://git-scm.com/docs/git-config/#Documentation/git-config.txt-XDGCONFIGHOMEgitconfig

fix(cli): use container user to setup git config

---

.devcontainer/Dockerfile

- Installs missing protobuf compiler in devpod devcontainer image
- refactors dockerfile 
- updates go version

Add protobuf support to devcontainer

---

pkg/ssh/config.go
pkg/ssh/config_test.go

Prepending the section to the file breaks include statements because ssh
will interpret these as scope to the first encountered host which would
be the last DevPod workspace host.

fix(cli): write DevPod ssh config section before first host

---

cmd/pro/add/cluster.go

Currently there is no way for user to know what argument this command expects just from `--help` message.

Add <cluster-name> to `devpod pro add cluster` command usage

---

e2e/tests/up/up.go
pkg/workspace/workspace.go

This PR fixes the issue when starting a workspace using a branch identifier by first checking for `@` in the repo name and parsing the branch name appropriately.
I have tested the changes by first replicating the issue:
```
./devpod-cli up https://github.com/moderneinc/moderne-cluster-build-logs@dependabot/pip/Clustering/torch-2.2.0
➜  devpod git:(POD-755/fix-up-when-branch-contains-slash) ✗ ./devpod-cli list                                                                                             
NAME                  |                                               SOURCE                                               | MACHINE | PROVIDER |  IDE   | LAST USED |   AGE    
----------------------------------------+---------------------------------------------------------------------------- …
```

POD-755: Fix workspace ID when branch is specified

---

cmd/agent/workspace/up.go
cmd/helper/helper.go
cmd/helper/ssh_git_clone.go
pkg/types/types.go

proxy git ssh traffic through our internal client because openssh might not
be installed in the target environment.
If we detect an external SSH key, we pass the GIT_SSH_COMMAND to git,
pointing to the new `devpod helper ssh-git-clone` command.

fix(cli): ssh based auth with external key

---

pkg/ide/jetbrains/generic.go

This PR adds a check to ensure intilliJ returned a 200 or 201 response code when downloading the IDE binary. This allows us to provide better error handling by providing the status code in the logs. This could be caused by using a bad version string to build thew download URL.
This PR was tested using `./devpod-cli up --ide intellij examples/simple` and ensuring the intillJ IDE was installed and launched.

POD-771: Check response code is successful when installing intilliJ based IDE

---

pkg/ide/fleet/fleet.go

This PR introduces an additional IDE option for fleet to indicate which version to install.
```
➜  devpod git:(POD-758/specify-fleet-version) ✗ ./devpod-cli ide options fleet
NAME      |          DESCRIPTION           |                                                   DEFAULT                                                    | VALUE  
-----------------+--------------------------------+--------------------------------------------------------------------------------------------------------------+--------
DOWNLOAD_AMD64 | The download url for the amd64 | https://download.jetbrains.com/product?code=FLL&release.type=preview&release.type=eap&platform=linux_x64     |        
| install script                 | …
```

POD-758: Allow user to specify fleet version

---

pkg/devcontainer/build.go

This PR fixes an issue a user had due to them specifying a build target in devcontainer.json that was not present in the Dockerfile. This PR solves the issue by validating the Dockerfile before deploying.

POD-769: Check build target exists in Dockerfile

---

cmd/pro/provider/delete.go
cmd/pro/provider/helper.go
cmd/up.go

Pro provider attempts to delete the CRD instead of calling the
workspace instances `/delete` endpoint on the runner.
This allows us to hook into the ownership mechanism without granting all
project users access to the `devpodworkspaceinstances/delete`
subresource.
In effect this allows all project users to delete their own workspaces
but not others. Admins can still delete all workspaces

fix(pro): delete ownded workspace

---

pkg/devcontainer/helpers.go

POD-768 | Update devcontainer helper funcs

---

pkg/driver/docker/docker.go

This PR addresses the issue outlined in https://github.com/loft-sh/devpod/issues/1197
Effectively this PR automatically adds the appropriate `--gpus-all` flag to the run args since this is the defined behaviour by the dev container spec

POD-819: Add --gpus=all if host requirments contain GPU

---

cmd/agent/workspace/up.go
cmd/up.go
pkg/devcontainer/compose.go
pkg/devcontainer/config.go
pkg/devcontainer/crane/run.go
pkg/devcontainer/prebuild.go
pkg/devcontainer/run.go
pkg/provider/workspace.go

POD-779 | Initial integration of devpod-crane

---

pkg/agent/inject.go

**Improvement: Enhanced Logging for Download URLs**
This PR improves the logging of the full download URL in the `downloadAgentLocally` function, addressing potential issues where incomplete or incorrect URLs lead to errors such as 404.
This change follows up on Issue #1240 where it was discussed that the current logging might not be sufficient for diagnosing certain network-related issues.
Closes #1240.

Use fullDownloadURL for clarity in downloadAgentLocally function

---

pkg/git/git.go
pkg/git/git_test.go

Part of POD-821
Git supports running git pull on local repositories using file:///path/to/repo url pattern

POD-821 | Support `file://` ulr pattern when normalizing repo URL

---

cmd/up.go
pkg/ssh/config.go
pkg/ssh/config_test.go

Users can specify a different location for the devpod directory other than
`~/.devpod` either by using the global flag `--devpod-home` or setting
the `DEVPOD_HOME` environment variable from DevPod Desktop or in their
shell.
This PR adds --devpod-home to the ssh config we generate after running
`devpod up ..` if it is set.
Because IDE's usually expect an ssh command, omitting the flag resulted
in non-functioning workspace.
Added another unit test for the ssh config

fix(cli): add --devpod-home to ssh config

---

docs/pages/developing-in-workspaces/dotfiles-in-a-workspace.mdx

Fixing a small typo in `Personalizing a Workspace` chapter.

fix: small typo in dotfiles-in-a-workspace.mdx

---

pkg/provider/dir.go

This PR fixes the issue reported in https://github.com/loft-sh/devpod/issues/1271
Effectively when using a repo without a .devcontainer.json, os.WriteFile creates a new file with permissions 600, instead of 644.
Looking at two examples locally
```
➜  devpod git:(feature/fix-linux-perm-issue) ✗ ls -la .devcontainer 
total 16
drwxr-xr-x  2 arthur arthur 4096 Sep  3 15:01 .
drwxr-xr-x 18 arthur arthur 4096 Sep 18 10:43 ..
-rw-r--r--  1 arthur arthur  292 Aug 23 16:34 devcontainer.json
-rw-r--r--  1 arthur arthur 1851 Sep  3 15:01 Dockerfile
➜  devpod git:(feature/fix-linux-perm-issue) ✗ ls -la ../devpod-example-devops/          
total 28
drwxr-xr-x  4 arthur arthur 4096 Sep 18 15:28 .
drwxr-xr-x 13 arthur arthur 4096 Sep 18 15:27 ..
-rw-r--r--  1 arthur arthur  443 Sep 18 15:28 …
```

Use correct file permission

---

cmd/agent/workspace/install_dotfiles.go

There is an example:
```go
package main
import (
"fmt"
"strings"
)
func main() {
cmd := struct {
InstallScript string
}{
InstallScript: "./example/script.sh",
}
commandOld := "./" + strings.TrimPrefix("./", cmd.InstallScript)
fmt.Println("old Constructed command:", commandOld)
commandNew := "./" + strings.TrimPrefix(cmd.InstallScript, "./")
fmt.Println("new Constructed command:", commandNew)
}
```
Output:
```
old Constructed command: ././
new Constructed command: ./example/script.sh
```
https://go.dev/play/p/OpHgx2LHtsp

fix: fix wrong parameter order

---

cmd/pro/start.go

Currently we have CLI arguments `reset` and `reuse-values` for the `pro start` command. These values are used to determine if the `helm upgrade` command should add `--reuse-values`, except we always add this since it is in the base args. Instead we should allow it to be added based on our CLI args

Allow reuse-values to be specified by CLI params

---

desktop/package.json
desktop/src/views/Settings/Settings.tsx
desktop/yarn.lock

This sorts the releases based on the tag, in descending order based on the semver.

Sort release versions according to semver

---

e2e/tests/up/up.go
examples/feature/afeature/install.sh
pkg/workspace/workspace.go

This PR fixes the `ToID` method to support PR references, when a PR is now used, the ID of the workspace will be `PR{id}`

Fix PR references

---

cmd/up.go

A user reported an error setting up the loft platform
https://app.usepylon.com/issues?conversationID=4a04f1ed-4a71-47e9-8b15-46edea30fdb3
Unfortunately, we didn't log or return the error so it is difficult to debug. This PR addresses the problem by wrapping the platform error and returning it.
NOTE: Is returning the error correct? I was unsure on expected behaviour, if we can't get the executable or port number we seem to return the error. But if the loft platform access error'd then we simply logged it. If we should NOT return the error I can update the PR to simply log the wrapped error.
UPDATE: I removed returning the error as this could cause more trouble than solve until we know why the bellow happens.
UPDATE: I reproduced the error locally by simply running `devpod up …

Log and wrap error when setting up loft platform

---

pkg/devcontainer/config/parse.go

My previous PR to fix this only changed the file permission of the workspace folder, the actual .devcontainer.json still had 0600. This PR changes the file perm to 0644.
Output of reproducing the error then fixed using this build.
```
➜  ~ devpod up --id testperm https://github.com/bkneis/LLCoinJ
12:40:19 info Creating devcontainer...
12:40:19 info Clone repository
12:40:19 info URL: https://github.com/bkneis/LLCoinJ
12:40:20 done Successfully cloned repository
12:40:20 info Couldn't find a devcontainer.json
12:40:20 info Try detecting project programming language...
12:40:20 info Detected project language 'JavaScript'
12:40:20 info Inspecting image mcr.microsoft.com/devcontainers/javascript-node
12:40:20 info Image mcr.microsoft.com/devcontainers/javascript-node not found
12:40:20 info …
```

POD-919: Use correct file permission for generated .devcontainer.json

---

cmd/ssh.go
pkg/devcontainer/sshtunnel/sshtunnel.go
pkg/gpg/gpg_forwarding.go
pkg/ssh/helper.go
pkg/tunnel/container.go
pkg/tunnel/services.go

Having similar options as SetEnv and SendEnv from the ssh client can be useful.
This PR adds those options to the ssh command.

Add send-env and set-env options to ssh command

---

cmd/build.go
cmd/delete.go
cmd/export.go
cmd/ide/use.go
cmd/logs.go
cmd/ssh.go
cmd/status.go
cmd/stop.go
cmd/up.go

Parameter containing the path to the workspace or the name to which the command shall be applied to are missing.

Improve command line help

---

desktop/src-tauri/src/custom_protocol.rs

This feature caused issues on both linux and windows. We should still be
able to properly detect issues by checking out the application logs

fix(desktop): print warning if we can't parse custom protocol instead of showing error in UI

---

cmd/agent/workspace/setup_gpg.go
cmd/ssh.go
pkg/gpg/gpg_forwarding.go

Some devcontainer features, like docker-in-docker, mount a tmpfs at
/tmp. During workspace setup with gpg agent forwarding enabled we attempt
to link the initial socket path, usually mimicking the actual path on
the users host machine, to /tmp/S.gpg-agent. Because /tmp _could be_ on
a different partition, hardlinking fails.
Changed the implementation to symlink instead. In my testing this didn't
change the behaviour, if issues arise we know where to look ;)

fix(gpg): use symlink when setting up the gpg socket in the workspace instead of hardlink

---

pkg/devcontainer/setup/lifecyclehooks.go

As discussed in https://github.com/loft-sh/devpod/pull/1313#issuecomment-2416787129, this PR avoids a hardcoded assumption from the lifecycle scripts that the devpod is built under a root user.
Building the devpod under a non-root user can be important in restricted kubernetes corporate environments. While currently creating devpods under a non-root user in kubernetes requires [some further hacks](https://github.com/nrontsis/devpod-example-go/compare/63cc83c...main), this PR removes a blocking certain aspect of it, allowing for creating a devpod as per the following demo. Before this PR, the building of the devpod would stop because `"su", user, "-c", command.Quote(c)` would be called by the run lifecycle hooks logic
```bash
devpod provider add kubernetes k8s-demo
devpod provider …
```

Don't hardcode root when running lifecycle scripts

---

.github/workflows/stale.yaml

I was working through some issues and think it would be nice to have some pipeline clear old issues that are not relevant. I copied this from
https://docs.github.com/en/actions/use-cases-and-examples/project-management/closing-inactive-issues
Is 3 months long enough? Any issues labelled as an enhancement or assign / in progress will be ignored so we can keep long lived feature requests for the road map. I think if a bug goes 3 months and either no one can reproduce or the reporter does not respond closing it is safe.

Add github workflow to mark issues as stale then delete after 2 months

---

cmd/agent/container/setup.go
cmd/up.go
pkg/config/ide.go
pkg/ide/ideparse/parse.go
pkg/open/open.go

Tested using ./devpod-cli --ide jupyterdesktop --id j5 up https://github.com/microsoft/vscode-remote-try-python
Since we already have the jupyter server logic we only needed to find and enable the client :)

Add experimental support for jupyter desktop

---

pkg/devcontainer/compose.go
pkg/devcontainer/prebuild.go
pkg/driver/docker.go
pkg/driver/docker/docker.go

Prebuilds did not work for docker compose since it's build pipeline assumed the image name, which is of course nil when using the build tag. The fix was to provide the default name docker-compose gives the the service (projectName-serviceName) and tag the built container as the devcontainer before pushing. Tested locally using docker provider
Fixes https://github.com/loft-sh/devpod/issues/1025

Fix prebuilds for docker compose

---

pkg/driver/docker/docker.go

This PR is a tentative implementation of the UpdateRemoteUserID handling.
The reference implementation uses an additional dockerfile (https://github.com/devcontainers/cli/blob/main/scripts/updateUID.Dockerfile) to create a new image using the container image created previously.
I don't think this approach works well with prebuilding feature of devpod. So I decided to amend the
container after it has been created. 
In some case, this modification may make the same uid gid to be used twice for 2 users and 2 groups but in the end it shall not impact the way the container work in the end. 
This also solves #1284.

Implement UpdateRemoteUserID handling

---

cmd/agent/container/setup.go
cmd/up.go
pkg/config/ide.go
pkg/driver/docker/docker.go
pkg/ide/ideparse/parse.go
pkg/ide/jetbrains/dataspell.go
pkg/ide/jetbrains/goland.go

Not yet tested due to licence issues

Implement experimental support for data spell

---

cmd/up.go
pkg/config/ide.go
pkg/ide/ideparse/parse.go
pkg/ide/zed/zed.go

Fixes https://github.com/loft-sh/devpod/issues/1185
This PR adds experimental support for zed.  Please note, according to [the docs](https://zed.dev/docs/remote-development#known-limitations) remote development in zed does not support extensions. So I have not added an "Install" function to download and run the zed remote server on the container like we do vscode or jetbrains

Implement experimental support for zed

---

cmd/build.go
pkg/devcontainer/build.go
pkg/devcontainer/config/build.go
pkg/devcontainer/prebuild.go
pkg/driver/docker/build.go
pkg/driver/docker/docker.go
pkg/image/image.go
pkg/provider/workspace.go

Adds new build cli flag `tag` that will tag the image with the user defined tag and then push
Example CLI command
`./devpod-cli build . --devcontainer-path ./devcontainer.json --force-build --debug --tag test,arm64`

Adds ability for user to define additional tags for images

---

cmd/pro/create_workspace.go
cmd/pro/list_workspaces.go
cmd/pro/update_provider.go
cmd/pro/update_workspace.go
cmd/provider/options.go
e2e/framework/server_utils.go

fix some function names in comment

chore: fix some function names in comment

---

cmd/machine/create.go
cmd/machine/delete.go
cmd/machine/ssh.go
cmd/machine/start.go
cmd/machine/status.go
cmd/machine/stop.go
cmd/provider/add.go
cmd/provider/delete.go
cmd/provider/update.go
cmd/provider/use.go

Positional arguments like the machine name or provider name are undocumented in the CLI. This commit adds them to the "Use" string so that they show up with the --help flag.

Add positional arguments to CLI usage string

---

pkg/ide/zed/zed_linux.go

This PR outputs the xdg-open output as debug if the command fails to help linux users debug xdg issues. Fixes https://github.com/loft-sh/devpod/issues/1448

Print xdg output for linux

---

cmd/build.go
cmd/up.go
pkg/agent/workspace.go
pkg/git/clone.go
pkg/provider/workspace.go

First of all -- amazing tool folks. Great work.
My use case involves using git submodules to reuse a .devcontainer directory across many git projects. Devpod currently fails as before this PR there is no way to do this. This PR aims to add a `git-clone-recursive-submodules` option to remedy this.
To this aim, I've refactored `git/clone.go` with the options pattern, which should make any future git option updates trivial, and implemented the passing of this option as one of them.
I set up a little test repo with the scenario:
```
【=◈︿◈=】@ C02FK0TXML7L ➜  tree -a
.
├── .devcontainer # is a submodule
│   ├── .git
│   └── devcontainer.json
└── main.go
```
https://github.com/charlysotelo/devcontainer-submodule-test
Here you can see the tool currently failing to find my submoduled …

feat: git clone recursive submodules option

---

cmd/agent/container/credentials_server.go
pkg/tunnel/services.go

Fixes https://github.com/loft-sh/devpod/issues/1438
Not sure how to test this one. I ran up using the problematic workspace and could SSH and use my git credentials. But since my signing key doesn't cause an issue I can't replicate. But I can confirm the base64 decode / encode works

Base 64 encode and decode signing key

---

pkg/devcontainer/build.go
pkg/image/image.go

Fixes https://github.com/loft-sh/devpod/issues/1490
I can't test this though since I am not on ARM :(
I believe there should be a follow up task in improving how we get the image from the registry for kubernetes provider. Currently there are other instances of image.GetImage but have no way of knowing the arch yet. Most other instances also only need to know if the image exists which can be done more cost effectively then getting the entire image. Additionally performing this check requires the local user to be authenticated to the registry.

Detect arch when getting image for prebuild

---

cmd/provider/set_options.go

fix(desktop): do not block specifying options if command is used from desktop. The options will be filled in later

---

hack/rebuild.sh

Simple fix - if TMPDIR isn't set, default it to /tmp
resolves **https://github.com/loft-sh/devpod/issues/1510**

Provide a default value for TMPDIR in the case none is given

---

docs/pages/other-topics/telemetry.mdx
pkg/telemetry/collect.go

With the current model described at <https://devpod.sh/docs/other-topics/telemetry#telemetry-opt-out-process>, a CLI user wanting to opt out of telemetry completely needs to remember to set the TELEMTRY option for every new context.
This PR adds an additional environment variable as a method to disable telemetry regardless of the current context. This is a common approach among open-sourced CLI programs.

cli: add an environment variable to disable telemetry globally

---

cmd/agent/workspace/up.go
pkg/agent/workspace.go

POD-1217 | Fix rebuilding workspace when project clone failed

---

.devcontainer/devcontainer.json
.devcontainer/post_create.sh
.github/devcontainer/Dockerfile
.github/devcontainer/devcontainer.json
.github/workflows/build-devcontainer-image.yaml

Splits the devcontainer into two distinct parts: one for building the
image and one for consuming and adding lifecycle commands.
The image-building devcontainer.json uses devcontainer features and
populates the `ghcr.io/loft-sh/devpod:dev` image.
The top-level devcontainer.json consumes the image and adds lifecycle
commands and potentially other properties that don't force the image to
change to it.
Also added a couple of smaller niceties

chore(dev): improve devcontainer setup

---

pkg/agent/tunnelserver/tunnelserver.go
pkg/gitcredentials/gitcredentials.go

In some scenarios the host machines git config sets `credential.useHttpPath=true` but the git config in either the agent or actual workspace doesn't.
Until now this would break git credential forwarding because we wouldn't provide the `path` component to the machines git credential helper.

fix(git): add support for `credential.useHttpPath`

---

pkg/devcontainer/run.go

fix(devcontainer): use the default shell on Windows for `initalizeCommand`

---

.github/workflows/release.yaml

The release successfully built the .deb package, but a previous step already uploaded as a build asset - https://github.com/loft-sh/devpod/actions/runs/12784785685/job/35638481557#step:22:85
Yet you can see the asset here - https://github.com/loft-sh/devpod/releases
This PR remove the manual deb upload

Remove deb upload

---

cmd/pro/provider/up.go
cmd/pro/provider/update/workspace.go
pkg/ide/vscode/open.go
pkg/platform/instance.go

Changes the template behaviour for pro instances like so:
1. If template is not versioned _always_ keep the workspace in sync
with template, even if that means rescheduling due to workspace
changes
2. If the template is versioned and the workspace uses an explicit
version we keep the workspace up to date with the template unless a
new version is available. We expect versioned templates to introduce
changes through a new version, not by updating an existing version
In addition to that we now wait until the server applied parameter
changes instead of assuming it did in time. This fixes a race condition
where the parameter changes wouldn't be applied if the controller took
more than a couple ms

fix(pro): always check for available template updates and wait for changed parameters to be applied

---

pkg/ide/zed/zed.go
pkg/ide/zed/zed_linux.go

This fixes an issue where project opened in Zed are opened as `//workspace/project/` instead of `/workspace/project/`. generally, the double slashes doesn't seem to prevent Zed to function. However, a few alert may arise in the logs depending of the used LSP and extensions.

fix(Zed): remove the double leading slashes on project

---

docs/pages/getting-started/install.mdx

OSS user discovered windows install failed due to missing dependency - https://github.com/loft-sh/devpod/issues/1573
This PR updates the docs to inform users of the required package

Update docs for windows dependency

---

examples/compose/.devcontainer.json
pkg/devcontainer/compose.go

Fixes https://github.com/loft-sh/devpod/issues/1554
The issue was that the initial up logic that ran docker-compose iterated through `runServices` and only added those to the upArgs (line 372). The condition when the container already existed (a re run of up) did not do this (line 167). The fix was to add the same logic to add to upArgs only those services defined by runServices. Additionally I refactored it to a function

Refactor runServices upArgs logic

---

pkg/agent/agent.go

The problem was that we correctly put the uploaded local folder under
the workspace directory /var/lib/loft/devpod/$WORKSPACE_ID/agent/.. but
when we established the SSH connection we attempted to create the actual
local workspace folder on the runner side.
Because we usually only have write access to /var/lib/loft remotely this
causes permission issues and `devpod ssh` to fail.

fix(pro): local folder upload works properly now with pro

---

docs/pages/getting-started/install.mdx
docs/pages/how-it-works/deploy-machines.mdx
docs/pages/managing-machines/what-are-machines.mdx

- Just minor updates to make language a bit clearer

Minor updates for clarity

---

cmd/agent/container/network_daemon.go
cmd/agent/container/setup.go
cmd/machine/ssh.go
cmd/ssh.go
cmd/up.go
pkg/devcontainer/setup.go
pkg/platform/config.go
pkg/ssh/helper.go
pkg/ssh/server/ssh.go

Fixes POD-1277
Example container state when running workspace
```
root ➜ /go $ ps -aux --forest
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         549  0.0  0.0   7616  6832 pts/4    Ss   13:45   0:00 bash
root         644  0.0  0.0   8160  3948 pts/4    R+   13:46   0:00  \_ ps -aux --forest
root           1  0.0  0.0   2316  1184 ?        Ss   13:45   0:00 /bin/sh -c echo Container started trap "exit 0" 15  exec "$@" while sleep 1 & wai
root         107  1.2  0.5 1328728 90264 ?       Sl   13:45   0:00 /usr/local/bin/devpod agent container network-daemon --access-key n2Z5MHx3EJRoFGf
root         115  0.7  0.4 1328216 72484 ?       Sl   13:45   0:00 /usr/local/bin/devpod helper ssh-server --track-activity
root         142  0.6  0.4 1327960 71172 ? …
```

POD-1277 | SSH sessions and proxy full support 

---

cmd/ssh.go

fix: enclose in quotes the GPG key identifier in gpg-agent setup

---

cmd/agent/container/setup.go
cmd/agent/workspace/install_dotfiles.go
cmd/build.go
cmd/helper/get_workspace_config.go
cmd/up.go
pkg/agent/tunnel/tunnel.proto
pkg/agent/tunnelserver/proxyserver.go
pkg/agent/tunnelserver/tunnelserver.go
pkg/agent/workspace.go
pkg/config/context.go
pkg/devcontainer/helpers.go
pkg/git/clone.go
pkg/git/git.go
pkg/gitcredentials/gitcredentials.go
pkg/provider/workspace.go

Enables users to set the `SSH_STRICT_HOST_KEY_CHECKING` context option to tighten security for ssh based git clones

chore(security): add context option to set StrictHostKeyChecking to yes for ssh based git operations

---

docs/pages/getting-started/install.mdx

This is useful to workaround #1410.

docs: Add a Fedora package name to install doc

---

community.yaml
docs/pages/managing-providers/add-provider.mdx

Due to the [sunsetting](https://deploy.equinix.com/blog/sunsetting-equinix-metal/) of Equinix Metal at the end of June 2026 this DevPod Provider will not be maintained anymore!

doc: remove equinix provider (#2)

---

.github/workflows/release.yaml

Previous release failed as one of the paths was wrong - https://github.com/loft-sh/devpod/actions/runs/13584200654/job/37975577427#step:24:68

Fix path to meta info

---

desktop/src-tauri/tauri-flatpak.conf.json

The previous flatpak build failed - https://github.com/loft-sh/devpod/actions/runs/13651396251/job/38160600315
I think the simplest fix is to rename the binary in the flatpak manifest here - https://github.com/loft-sh/flathub/blob/org.loft.devpod/sh.loft.Devpod.yaml#L45
Since flatpak is the one enforcing this specific naming convention I think we should revert the name to be the same as mac and windows but rename it to `sh.loft.Devpod` for flatpak

Remove flatpak binary name change

---

desktop/flatpak/DevPod.metainfo.xml
desktop/flatpak/sh.loft.devpod.tmpl
desktop/package.json

This PR fixes DevPod.metainfo.xml that the flatpak build uses to match against the id and desktop file name to the flatpak app id. I also updated the flatpak manifest template that will be used once the flathub PR is merged.

Update flatpak manifest with correct app id

---

cmd/up.go

This PR fixes rstudio when port 8787 is not available locally.
Currently if port 8787 is not available locally, for example when rstudio is running with another workspace, the next free port is found. This is what we want locally, but the issue is the port in the workspace should remain 8787.

Use 8787 instead of enumerated port

---

pkg/driver/kubernetes/client.go
pkg/driver/kubernetes/driver.go

When the kubernetes driver was moved into devpod, a customer discovered an issue where the PVC is always scheduled in the default namespace "devpod". This could be reproduced by deploying any workspace using a space template.
This PR fixes the issue by first checking the kube config, and if available use this namespace, instead of the default.
I tested this against a local platform with the only change being this build, using a space template. I also validated the namespace being used in the logs

Check kube config for the namespace before using the default

---

desktop/src/components/Terminal/Terminal.tsx

This PR fixes copy and pasting from the desktop app logs.
The issue was a known xterm limitation in that ctrl +c is mapped to the terminals key handlers. Previously we relied on document.execCommand("copy") but this is deprecated in web view. Looking at the dependency GH issues https://github.com/xtermjs/xterm.js/issues/2478 and https://github.com/xtermjs/xterm.js/issues/292 a user offered an alternative solution which is to use `attachCustomKeyEventHandler` and return false on Ctrl + C to prevent the terminal key binding being used on ctrl +c.
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

Fix clipboard in xterm
